### ISSUE TITLE
Use normal ethermine convention with reported hash rate

### ISSUE THREAD

**Issue by benkofk** [nrpatten/expanse-proxy#2]
Hi there,

I love this, very cool. I liked Sammy's too, but with 3GH, I don't really want to solo mine ethereum which brings me here. 

I have over 90 rigs and want to switch them to expanse with this, but the naming convention means that I will have to go to every rig and change batch files from

ethminer http://xxx.xxx.xxx.xxx:xxxx/001
   to
ethminer http://xxx.xxx.xxx.xxx:xxxx/miner/001/difficulty

Does the /miner/ really need to be there? Also could the difficulty not be based on half of the reported hash rate (or something similar, i'm sure you know better) or optionally they could specify like now?

**Comment by nrpatten** [comment]
@benkofk I will have to change to code in the backend for this, I dont realy have time at the moment but i will push the fix once i get a chance.
Also pull the latest commit for stats fix.

**Comment by nrpatten** [comment]
@benkofk Your also welcome to mine on http://pool.expanse.tech/  PROP payouts and 0% fee. i run this pool for expanse tech and there will never be a fee to mine on the pool.

**Comment by benkofk** [comment]
Thanks for the reply, it seems that despite expanse's value has skyrocketed, according to the calculator on the expanse tech website 6gh will only return 13 EXP an hour :scream: which is still below ethereum in overall value so no need at the moment. I think lots of people are mining it through nicehash.

**Comment by slavserver** [comment]
hi, why not worked this page stats? http://clona.ru:8080/www_test/stats.html

**Comment by nrpatten** [comment]
`Error: CONNECTION ERROR: Couldn't connect to node http://127.0.0.1:9656.` 👍

**Comment by slavserver** [comment]
My local ip 192.168.0.36. This adress set config. Ok, view work ver http://clona.ru:8080/  and http://clona.ru:8080/stats.html
or in the configuration should be exactly 127.0.0.1?

**Comment by nrpatten** [comment]
What command do you use to start gexp? and what ip is in https://github.com/nrpatten/expanse-proxy/blob/master/config.example.json#L24 because the backend can contact gexp but the javascript cant.

**Comment by slavserver** [comment]
:Rs
gexp.exe --rpc --rpcaddr 127.0.0.1 --rpcport 9656 --port 42786 --datadir C:\SLAVA_NODA\EXP_WALLET\resources\node\gexp\Expanse --maxpeers 100 console 
goto :Rs

I use gexp. ip node fixed to 127.0.0.1
config.json edited url ":" http://127.0.0.1:9656 ",

Unfortunately that does not work = ((((

**Comment by slavserver** [comment]
http://clona.ru:8080/server.html
all ok

http://clona.ru:8080/stats.html
failed

**Comment by nrpatten** [comment]
https://github.com/nrpatten/expanse-proxy/blob/master/www/js/stats.js#L3 must be the same ip:port (127.0.0.1:9656)

Also add --rpccorsdomain "*" to your gexp start params

```
gexp.exe --rpc --rpcaddr 127.0.0.1 --rpcport 9656 --port 42786 --rpccorsdomain "*" --datadir C:\SLAVA_NODA\EXP_WALLET\resources\node\gexp\Expanse --maxpeers 100 console
goto :Rs
```

**Comment by slavserver** [comment]
$(document).ready(function() {
    var web3 = new Web3();
    web3.setProvider(new web3.providers.HttpProvider('http://127.0.0.1:9656'));


:Rs
gexp.exe --rpc --rpcaddr 127.0.0.1 --rpccorsdomain "*" --rpcport 9656 --port 42786 --datadir C:\SLAVA_NODA\EXP_WALLET\resources\node\gexp\Expanse --maxpeers 100 console 
goto :Rs



not work

**Comment by nrpatten** [comment]
Try:

```
gexp.exe --port "42786" --rpc --rpcaddr "162.243.239.186" --rpcport "9656" --rpccorsdomain "*" --datadir C:\SLAVA_NODA\EXP_WALLET\resources\node\gexp\Expanse --maxpeers 100 console
```

If that dose not work try to redownload master and start it with defaults.

**Comment by slavserver** [comment]
sorry/ all works/tnx

**Comment by slavserver** [comment]
parity for the client, there are differences?

**Comment by nrpatten** [comment]
Parity "Shoud" work i have not tested it but.

**Comment by slavserver** [comment]
Hey. I load node etc, eth. I need everything to work. It showed a balance of the pool, and all outgoing transactions. windows 7 system, internal ip 192.168.0.36. Virtual servers are configured. do the work, you will send 100 etc

etc node port 9445 web 80
expnode port standart web 8080
